print a clean error message and config.yml file path when yaml.load() fails
Summary:
when YAML.load fails, we should return more actionable information and clear remediation instruction.

```
ConfigYamlFileParsingError: ./config.yaml is not a valid YAML file. Suggested remediation: validate the content of ./config.yaml on http://www.yamllint.com/.
Cause: while parsing a flow node
expected the node content, but found '<stream end>'
```

In this example, the invalid input yaml was generated by PCS for canary. But invalid files could also be prepared by partners.
 https://fb.workplace.com/groups/331044242148818/posts/422172903035951/?comment_id=440970687822839

Reviewed By: jrodal98

Differential Revision: D34733332

fbshipit-source-id: b13d055a7dc3cfb69ab99e1bf3f05c293e518e04