Fix fbpcs/onedocker image after migrated to self hosted runner
Summary:
The image failed to built:
1.ERROR: Unable to find docker image fbpcf/ubuntu:latest.  Please clone and run https://github.com/facebookresearch/fbpcf/blob/master/build-docker.sh -- Adding a -f so it will download the most recent one
2.During testing, I also notice the tag for private-id always need to be:latest( we cannot tag it as :rc)

Reviewed By: corbantek

Differential Revision: D31508903

fbshipit-source-id: ceedd382ab5fe8bb6515ccf98c6acc15a0601d15