Fix fbpcs/onedocker image after migrated to self hosted runner (#153)
Summary:
Pull Request resolved: https://github.com/facebookresearch/fbpcs/pull/153

The image failed to built:
1.ERROR: Unable to find docker image fbpcf/ubuntu:latest.  Please clone and run https://github.com/facebookresearch/fbpcf/blob/master/build-docker.sh -- Adding a -f so it will download the most recent one
2.During testing, I also notice the tag for private-id always need to be:latest( we cannot tag it as :rc)

Reviewed By: corbantek

Differential Revision: D31508903

fbshipit-source-id: 63a32df49fd045a38f528ee0d0369db3e128308e