Ignore unknown values in the Private Computation base Instance Schema - Add Support for rolling back the thrift service when new parameters are added. (#1907)
Summary:
Pull Request resolved: https://github.com/facebookresearch/fbpcs/pull/1907

## Context
We have been seeing a number of errors during this code freeze due to a newly added field to the Private Computation thrift service that does not handle being rolled back well. The field is written into a database object, that when read out, causes the following error:
2022-11-09 17:13:04,604 ERROR measurement.private_measurement.private_computation_service.handler:
```
[15502211744726] Error during getInstance: {'instances': {0: {'server_uris': ['Unknown field.']}, 1: {'server_uris': ['Unknown field.']}, 2: {'server_uris': ['Unknown field.']}, 4: {'server_uris': ['Unknown field.']}, 5: {'server_uris': ['Unknown field.']}, 6: {'server_uris': ['Unknown field.']}}}
Traceback (most recent call last):
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/measurement/private_measurement/private_computation_service/handler.py", line 289, in getInstance
    private_computation_instance_entity = await self._get_instance(
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/measurement/private_measurement/private_computation_service/handler.py", line 309, in _get_instance
    return await loop.run_in_executor(
  File "/usr/local/fbcode/platform010/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/fbpcs/private_computation/service/private_computation.py", line 324, in get_instance
    return self.instance_repository.read(instance_id=instance_id)
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/measurement/private_lift/repository/node_instance_repository.py", line 61, in read
    json_data = self.instance_type.loads_schema(instance_node.instance_json)
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/fbpcs/private_computation/entity/private_computation_instance.py", line 89, in loads_schema
    infra_config: InfraConfig = InfraConfig.schema().loads(
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/marshmallow/schema.py", line 756, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/dev/shm/uid-99/d344babe-seed-nspid4026533160_cgpid10927416-ns-4026533157/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'instances': {0: {'server_uris': ['Unknown field.']}, 1: {'server_uris': ['Unknown field.']}, 2: {'server_uris': ['Unknown field.']}, 4: {'server_uris': ['Unknown field.']}, 5: {'server_uris': ['Unknown field.']}, 6: {'server_uris': ['Unknown field.']}}}
```

## This Diff
This diff updates the instance base to ignore unknown fields by default when deserializing an object.

Differential Revision: D41193347

fbshipit-source-id: 923bab20ef7fc2bb2900107c125cc0f083225bda