Fix all dependencies needed by fbpcp (#1508)
Summary:
Pull Request resolved: https://github.com/facebookresearch/fbpcs/pull/1508

I landed D39024666 (https://github.com/facebookresearch/fbpcs/commit/0d9483bc29c080e8e32ac17220e110be67e7040e) this morning, but got a comment from jrodal98 that fbpcp has a lot of version locked dependencies. Turns out, the pip install was throwing some errors. I have fixed those in this diff.

For context, I saw the following errors when i ran a pip install:
```
ERROR: google-cloud-core 1.7.3 has requirement google-auth<2.0dev,>=1.24.0, but you'll have google-auth 2.11.0 which is incompatible.
ERROR: google-cloud-storage 1.30.0 has requirement google-auth<2.0dev,>=1.11.0, but you'll have google-auth 2.11.0 which is incompatible.
ERROR: fbpcp 0.3.0 has requirement schema==0.7.5, but you'll have schema 0.7.0 which is incompatible.
ERROR: fbpcp 0.3.0 has requirement tqdm==4.55.1, but you'll have tqdm 4.64.0 which is incompatible.
ERROR: fbpcp 0.3.0 has requirement urllib3==1.26.7, but you'll have urllib3 1.26.12 which is incompatible.
```

Reviewed By: jrodal98

Differential Revision: D39036022

fbshipit-source-id: 7edf8ca84c4c2405601ea9c451864f00bc65b15f