fix bolt config parsing bug (#1240)
Summary:
Pull Request resolved: https://github.com/facebookresearch/fbpcs/pull/1240

## What

* Fix a bug in bolt config parsing
    * if job_args isn't specified in the bolt_config, then the parsing doesn't work

> 104, in create_job_list
> poll_interval=job_specific_args.get(
AttributeError: 'list' object has no attribute 'get'

## Why

* job_args isn't specified in the github CI/CD bolt_config, so the bug is blocking the next release: https://github.com/facebookresearch/fbpcs/runs/7263335110?check_suite_focus=true

Reviewed By: joe1234wu

Differential Revision: D37738045

fbshipit-source-id: d17ca3358caa51c6cdfedcedb88c09563caf85fa