Fix error when lambda logs are missing in Cloudwatch (#1573)
Summary:
Pull Request resolved: https://github.com/facebookresearch/fbpcs/pull/1573

**What**

When lambda is not triggered and logs are missing in cloudwatch, download logs code fail with following traceback. This diff handles this failures and allows code to proceed when logs are missing,

```
(env) ankushksingh@ankushksingh-mbp download_logs % python3 download_logs.py
Traceback (most recent call last):
  File "/Users/ankushksingh/fbsource/fbcode/fbpcs/infra/logging_service/download_logs/cloud/aws_cloud.py", line 464, in get_latest_cloudwatch_log
    response = self.cloudwatch_client.describe_log_streams(
  File "/Users/ankushksingh/.local/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ankushksingh/.local/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_logs.py", line 498, in <module>
    a.upload_logs_to_s3_from_cloudwatch(
  File "download_logs.py", line 138, in upload_logs_to_s3_from_cloudwatch
    self._upload_lambda_logs(
  File "download_logs.py", line 304, in _upload_lambda_logs
    log_stream_name = self.get_latest_cloudwatch_log(
  File "/Users/ankushksingh/fbsource/fbcode/fbpcs/infra/logging_service/download_logs/cloud/aws_cloud.py", line 474, in get_latest_cloudwatch_log
    raise AwsCloudwatchLogStreamFetchException(f"{error_message}")
fbpcs.infra.logging_service.download_logs.cloud_error.cloud_error.AwsCloudwatchLogStreamFetchException: Couldn't fetch log streams for log group /aws/lambda/cb-data-ingestion-stream-processor-08sep22-djex: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
(env) ankushksingh@ankushksingh-mbp download_logs %
```

**Why**
In case lambda is not triggered before running Computation UI then download logs code will fail to get logs for all the components, which shouldn't be the case.

**Context**
https://docs.google.com/document/d/1cMD9IQ8uF6MS1PRvOh8cr-1el7MO952SjUanAzAGJzw/edit?usp=sharing

Differential Revision: D39515381

fbshipit-source-id: 013d2ce69af8835f2a30774fb700ca48474a0df2