kodiak: disable autocargo
Summary:
As c-ryan747 pointed out in [comment](https://www.internalfb.com/diff/D34934689 (https://github.com/facebookresearch/fbpcs/commit/669a2d0dd46646a9e96ac6551d3f2bf28d9c7fd3)?dst_version_fbid=1378859129226301&transaction_fbid=1599019110471197), this is breaking the crate import workflow.
```
[hzhou@devvm4385.prn0 ~/fbsource] fbcode/common/rust/cargo_from_buck/bin/autocargo
<...>
Error: While generating cargo files for targets path fbpcs/kodiak/TARGETS

Caused by:
    0: While preparing GenerationInput for targets TargetsPath { file: PathInFbcode("fbpcs/kodiak/TARGETS"), dir: PathInFbcode("fbpcs/kodiak") } and cargo in dir None
    1: When multiple rules map into a single Cargo.toml file there can be at most one rust_library rule. Library rules found: ["kodiak@rust", "kodiak"]
```

Reviewed By: jrodal98

Differential Revision: D35203918

fbshipit-source-id: 5aeb2e06793d26056d307a8507373ea1949e0e5c